'use client';
import {useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowDownToLine,ArrowRightLeft,Boxes,CheckCircle2,ChevronDown,ClipboardList,Download,FileSpreadsheet,LayoutDashboard,Menu,Plus,Search,Settings,ShoppingBag,Smartphone,Upload,UserRound,Users,X} from 'lucide-react';
import * as XLSX from 'xlsx';
const MODELS=['A06-64GB','A06-128GB','A07-64GB','A07-128GB','A16-128GB','A17-128GB'] as const; type Model=typeof MODELS[number];
type Tx={id:number;date:string;type:'Ravitaillement'|'Vente'|'Prêt entrant'|'Prêt sortant';team:string;agent:string;model:Model;qty:number;note:string};
const teams=[['Équipe Gombe','Patrick M.'],['Équipe Limete','Sarah K.'],['Équipe Ngaliema','David L.']];
const agents=[['Jean Mbuyi','Équipe Gombe'],['Grâce Ilunga','Équipe Gombe'],['Alain Kanku','Équipe Limete'],['Mireille Sefu','Équipe Limete'],['Chris Kalala','Équipe Ngaliema'],['Fanny Mbala','Équipe Ngaliema']];
const base:Record<Model,number>={'A06-64GB':42,'A06-128GB':29,'A07-64GB':34,'A07-128GB':26,'A16-128GB':18,'A17-128GB':11};
const seed:Tx[]=[['Vente','Équipe Gombe','Jean Mbuyi','A06-64GB',8,'Rapport validé'],['Vente','Équipe Limete','Alain Kanku','A07-128GB',5,'Rapport validé'],['Ravitaillement','Équipe Ngaliema','Chris Kalala','A16-128GB',6,'Bon #RAV-0821'],['Prêt sortant','Équipe Gombe','Grâce Ilunga','A17-128GB',3,'Vers Équipe Limete'],['Prêt entrant','Équipe Limete','Mireille Sefu','A17-128GB',3,'Depuis Équipe Gombe'],['Vente','Équipe Ngaliema','Chris Kalala','A06-128GB',7,'1 écart à vérifier'],['Vente','Équipe Gombe','Grâce Ilunga','A07-64GB',11,'Rapport validé']].map((x,i)=>({id:i,date:i<3?'2026-08-30':'2026-08-29',type:x[0],team:x[1],agent:x[2],model:x[3],qty:x[4],note:x[5]} as Tx));
function Pill({children,tone='green'}:{children:React.ReactNode,tone?:string}){return <span className={'pill '+tone}>{children}</span>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export default function Home(){
 const [view,setView]=useState<'dashboard'|'stock'|'reports'|'settings'>('dashboard'),[txs,setTxs]=useState(seed),[modal,setModal]=useState<'tx'|'agent'|'team'|null>(null),[toast,setToast]=useState(''),[search,setSearch]=useState('');
 const [type,setType]=useState<Tx['type']>('Vente'),[model,setModel]=useState<Model>('A06-64GB'),[team,setTeam]=useState(teams[0][0]),[agent,setAgent]=useState(agents[0][0]),[qty,setQty]=useState(1); const file=useRef<HTMLInputElement>(null); const [compare,setCompare]=useState<{name:string,rows:number,ok:number}|null>(null);
 const stats=useMemo(()=>MODELS.map(model=>{let plus=0,sold=0,lent=0;txs.filter(t=>t.model===model).forEach(t=>{if(t.type==='Ravitaillement'||t.type==='Prêt entrant')plus+=t.qty;if(t.type==='Vente')sold+=t.qty;if(t.type==='Prêt sortant')lent+=t.qty});return{model,initial:base[model],plus,sold,lent,left:base[model]+plus-sold-lent}}),[txs]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2600)}, total=stats.reduce((a,b)=>a+b.left,0),sold=stats.reduce((a,b)=>a+b.sold,0),low=stats.filter(x=>x.left<=10).length;
 const add=(e:React.FormEvent)=>{e.preventDefault();setTxs(v=>[{id:Date.now(),date:'2026-08-30',type,team,agent,model,qty,note:'Saisie manuelle'},...v]);setModal(null);flash('Mouvement enregistré et stock recalculé.')};
 const upload=async(f:File)=>{const book=XLSX.read(await f.arrayBuffer());const sheet=book.Sheets[book.SheetNames[0]];const data=XLSX.utils.sheet_to_json<(string|number)[]>(sheet,{header:1});const rows=data.slice(1).filter(r=>r.length);let ok=0;rows.forEach(r=>{if(r.some(v=>(MODELS as readonly string[]).includes(String(v).trim()))&&r.some(v=>txs.some(t=>t.qty===Number(v))))ok++});setCompare({name:f.name,rows:rows.length,ok});setView('reports');flash('Comparaison Excel terminée.')};
 const exportCsv=()=>{const body=['Date;Type;Équipe;Agent;Modèle;Quantité',...txs.map(t=>[t.date,t.type,t.team,t.agent,t.model,t.qty].join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+body]));a.download='rapport-ventes.csv';a.click()};
 const title=view==='dashboard'?'Vue d’ensemble':view==='stock'?'Stock & mouvements':view==='reports'?'Rapports & contrôle':'Paramètres';
 return <main><aside><div className="logo"><Smartphone/><div><b>StockPilot</b><small>Mobile Sales</small></div></div><nav><button className={view==='dashboard'?'on':''} onClick={()=>setView('dashboard')}><LayoutDashboard/>Tableau de bord</button><button className={view==='stock'?'on':''} onClick={()=>setView('stock')}><Boxes/>Stock & mouvements</button><button className={view==='reports'?'on':''} onClick={()=>setView('reports')}><ClipboardList/>Rapports & contrôle</button><label>ADMINISTRATION</label><button className={view==='settings'?'on':''} onClick={()=>setView('settings')}><Settings/>Paramètres</button></nav><div className="profile"><i>AM</i><span><b>Admin Manager</b><small>Administrateur</small></span><ChevronDown/></div></aside>
 <section className="main"><header><Menu className="menu"/><div><h1>{title}</h1><p>Suivi des ventes et du stock en temps réel</p></div><div className="actions"><button className="ghost" onClick={()=>file.current?.click()}><Upload/>Importer Excel</button><input ref={file} hidden type="file" accept=".csv,.xls,.xlsx" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><button className="primary" onClick={()=>setModal('tx')}><Plus/>Nouveau mouvement</button></div></header>
 {view==='dashboard'&&<div className="content"><div className="date"><span><b>Aujourd’hui, 30 août 2026</b><small>Dernière mise à jour il y a 3 min</small></span><button className="ghost" onClick={exportCsv}><Download/>Exporter</button></div><section className="kpis"><Kpi icon={<Boxes/>} label="STOCK DISPONIBLE" value={total} note="téléphones en main"/><Kpi icon={<ShoppingBag/>} label="VENTES DE LA PÉRIODE" value={sold} note="toutes équipes"/><Kpi icon={<Users/>} label="AGENTS ACTIFS" value="9/10" note="3 équipes terrain"/><Kpi icon={<AlertTriangle/>} label="ALERTES À TRAITER" value={low+2} note="stock bas et écarts" danger/></section><div className="grid"><section className="panel"><Head title="Situation du stock par modèle" text="Calcul automatique du stock restant"/><div className="stock-list">{stats.map(s=><div className="stock" key={s.model}><i><Smartphone/></i><span><b>{s.model}</b><small>{s.sold} vendus</small></span><em><u style={{width:Math.min(100,s.left/50*100)+'%'}}/></em><strong>{s.left}</strong><Pill tone={s.left<=10?'red':s.left<=20?'amber':'green'}>{s.left<=10?'Stock bas':s.left<=20?'À surveiller':'Disponible'}</Pill></div>)}</div></section><section className="panel"><Head title="Alertes & anomalies" text="Nécessitent votre attention"/><Alert icon={<AlertTriangle/>} title="Écart de rapport" text="Chris Kalala · A06-128GB" sub="Rapport : 8 · Système : 7"/><Alert icon={<Boxes/>} title="Stock critique" text="A17-128GB · 8 unités restantes" sub="Seuil minimum : 10 unités"/><Alert icon={<ClipboardList/>} title="Rapport non soumis" text="Fanny Mbala · Équipe Ngaliema" sub="Rapport du 29 août"/></section></div><section className="panel"><Head title="Activité récente" text="Derniers mouvements enregistrés"/><Table rows={txs.slice(0,5)}/></section></div>}
 {view==='stock'&&<div className="content"><section className="panel"><Head title="État consolidé du stock" text="Quantités sur l’ensemble des équipes et agents" action={<button className="primary" onClick={()=>setModal('tx')}><Plus/>Ajouter</button>}/><div className="scroll"><table><thead><tr><th>Modèle</th><th>Stock initial</th><th>Ravitaillement</th><th>Vendus</th><th>Prêtés</th><th>Restant</th><th>État</th></tr></thead><tbody>{stats.map(s=><tr key={s.model}><td><b>{s.model}</b></td><td>{s.initial}</td><td className="pos">+{s.plus}</td><td>{s.sold}</td><td>{s.lent}</td><td><b>{s.left}</b></td><td><Pill tone={s.left<=10?'red':s.left<=20?'amber':'green'}>{s.left<=10?'Rupture proche':'Disponible'}</Pill></td></tr>)}</tbody></table></div></section><section className="panel"><Head title="Historique des mouvements" text="Ventes, ravitaillements et prêts" action={<label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher…"/></label>}/><Table rows={txs.filter(t=>Object.values(t).join(' ').toLowerCase().includes(search.toLowerCase()))}/></section></div>}
 {view==='reports'&&<div className="content"><section className="import"><div><FileSpreadsheet/><h2>Comparer un rapport Excel</h2><p>Importez le rapport terrain. Le système compare automatiquement modèles et quantités avec les saisies de l’application.</p><button className="primary" onClick={()=>file.current?.click()}><Upload/>Choisir un fichier</button><small>CSV, XLS ou XLSX · 10 Mo max.</small></div>{compare?<div className="compare"><FileSpreadsheet/><b>{compare.name}</b><small>{compare.rows} lignes analysées</small><strong>{compare.rows?Math.round(compare.ok/compare.rows*100):100}%</strong><span>de similarité</span><Pill tone={compare.ok===compare.rows?'green':'amber'}>{compare.rows-compare.ok} différence(s)</Pill></div>:<button className="drop" onClick={()=>file.current?.click()}><Upload/><b>Déposez le rapport ici</b><span>ou cliquez pour parcourir</span></button>}</section><section className="panel"><Head title="Rapports journaliers" text="Suivi de soumission par équipe"/><div className="scroll"><table><thead><tr><th>Agent</th><th>Équipe</th><th>Date</th><th>Déclarées</th><th>Système</th><th>Écart</th><th>Statut</th></tr></thead><tbody>{agents.slice(0,5).map((a,i)=><tr key={a[0]}><td><b>{a[0]}</b></td><td>{a[1]}</td><td>30/08/2026</td><td>{[8,6,5,4,7][i]}</td><td>{[8,6,5,4,6][i]}</td><td>{i===4?'-1':'0'}</td><td><Pill tone={i===4?'red':'green'}>{i===4?'Écart détecté':'Conforme'}</Pill></td></tr>)}</tbody></table></div></section></div>}
 {view==='settings'&&<div className="content"><div className="tabs"><button className="on"><UserRound/>Agents</button><button><Users/>Équipes</button><button><Users/>Chefs de team</button></div><section className="panel"><Head title="Agents commerciaux" text="6 agents enregistrés dans 3 équipes" action={<button className="primary" onClick={()=>setModal('agent')}><Plus/>Créer un agent</button>}/><div className="cards">{agents.map((a,i)=><article key={a[0]}><i>{a[0].split(' ').map(x=>x[0]).join('')}</i><span><b>{a[0]}</b><small>{a[1]}</small><small>+243 810 23{i} 50{i}</small></span><Pill tone={i===5?'gray':'green'}>{i===5?'Inactif':'Actif'}</Pill></article>)}</div></section><section className="panel"><Head title="Équipes & chefs" text="Organisation commerciale" action={<button className="ghost" onClick={()=>setModal('team')}><Plus/>Créer une équipe</button>}/><div className="teams">{teams.map((t,i)=><article key={t[0]}><Users/><span><b>{t[0]}</b><small>Chef : {t[1]}</small><small>{i+3} agents</small></span><ChevronDown/></article>)}</div></section></div>}</section>
 {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><form className="modal" onSubmit={modal==='tx'?add:e=>{e.preventDefault();setModal(null);flash('Création effectuée avec succès.')}} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><span><h2>{modal==='tx'?'Nouveau mouvement':modal==='agent'?'Créer un agent':'Créer une équipe'}</h2><p>Renseignez les informations principales.</p></span><button type="button" onClick={()=>setModal(null)}><X/></button></div><div className="form">{modal==='tx'?<><Field label="Type"><select value={type} onChange={e=>setType(e.target.value as Tx['type'])}>{['Vente','Ravitaillement','Prêt entrant','Prêt sortant'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Modèle"><select value={model} onChange={e=>setModel(e.target.value as Model)}>{MODELS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Équipe"><select value={team} onChange={e=>setTeam(e.target.value)}>{teams.map(x=><option key={x[0]}>{x[0]}</option>)}</select></Field><Field label="Agent"><select value={agent} onChange={e=>setAgent(e.target.value)}>{agents.filter(x=>x[1]===team).map(x=><option key={x[0]}>{x[0]}</option>)}</select></Field><Field label="Quantité"><input type="number" min="1" value={qty} onChange={e=>setQty(+e.target.value)}/></Field><Field label="Date"><input type="date" defaultValue="2026-08-30"/></Field></>:modal==='agent'?<><Field label="Nom complet"><input required placeholder="Ex. Marie Kabeya"/></Field><Field label="Téléphone"><input required placeholder="+243…"/></Field><Field label="Équipe"><select>{teams.map(x=><option key={x[0]}>{x[0]}</option>)}</select></Field><Field label="Rôle"><select><option>Agent commercial</option><option>Chef de team</option></select></Field></>:<><Field label="Nom de l’équipe"><input required placeholder="Ex. Équipe Matete"/></Field><Field label="Chef de team"><select>{agents.map(x=><option key={x[0]}>{x[0]}</option>)}</select></Field></>}</div><footer><button type="button" className="ghost" onClick={()=>setModal(null)}>Annuler</button><button className="primary">Enregistrer</button></footer></form></div>}{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</main>}
function Kpi({icon,label,value,note,danger}:{icon:React.ReactNode,label:string,value:number|string,note:string,danger?:boolean}){return <article className="kpi"><i>{icon}</i><span><small>{label}</small><strong>{value}</strong><em>{note}</em></span><Pill tone={danger?'red':'green'}>{danger?'Action':'À jour'}</Pill></article>}
function Head({title,text,action}:{title:string,text:string,action?:React.ReactNode}){return <div className="head"><span><h2>{title}</h2><p>{text}</p></span>{action}</div>}
function Alert({icon,title,text,sub}:{icon:React.ReactNode,title:string,text:string,sub:string}){return <div className="alert"><i>{icon}</i><span><b>{title}</b><p>{text}</p><small>{sub}</small></span></div>}
function Table({rows}:{rows:Tx[]}){return <div className="scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Équipe / Agent</th><th>Modèle</th><th>Qté</th><th>Détail</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.date.split('-').reverse().join('/')}</td><td><i className="tx">{t.type==='Vente'?<ShoppingBag/>:t.type==='Ravitaillement'?<ArrowDownToLine/>:<ArrowRightLeft/>}</i>{t.type}</td><td><b>{t.team}</b><small className="sub">{t.agent}</small></td><td><b>{t.model}</b></td><td><b>{t.type==='Ravitaillement'||t.type==='Prêt entrant'?'+':'−'}{t.qty}</b></td><td><Pill tone={t.note.includes('écart')?'red':'gray'}>{t.note}</Pill></td></tr>)}</tbody></table></div>}
