'use client';

import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, Check, ChevronLeft, ChevronRight, CircleAlert, Copy, Database, Download, FileCheck2, FileText, Info, LoaderCircle, LockKeyhole, RefreshCw, Search, ShieldCheck, Sparkles, Upload, X } from 'lucide-react';

type Row = { imei: string; date: Date | null; valid: boolean; fo?: string; model?: string; connected?: boolean };
type Tone = 'success' | 'error' | 'info';
const dateRx = [/^(\d{1,2})[/.-](\d{1,2})[/.-](\d{4})$/, /^(\d{4})[/.-](\d{1,2})[/.-](\d{1,2})$/];
function safeDate(y:number,m:number,d:number){const x=new Date(y,m-1,d);return x.getFullYear()===y&&x.getMonth()===m-1&&x.getDate()===d?x:null}
function parseDate(v:string){let m=v.trim().match(dateRx[0]);if(m)return safeDate(+m[3],+m[2],+m[1]);m=v.trim().match(dateRx[1]);return m?safeDate(+m[1],+m[2],+m[3]):null}
function validImei(v:string){v=v.trim();if(!/^\d{15}$/.test(v))return false;let s=0;for(let i=0;i<15;i++){let n=+v[i];if(i%2){n*=2;if(n>9)n-=9}s+=n}return s%10===0}
function reason(v:string){v=v.trim();if(!/^\d+$/.test(v))return 'Caractères non numériques';if(v.length!==15)return '15 chiffres requis';return 'Clé de contrôle incorrecte'}
function parse(text:string){let date:Date|null=null;const out:Row[]=[];for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const d=parseDate(line);if(d){date=d;continue}out.push({imei:line,date,valid:validImei(line)})}return out}
function fmt(d:Date|null){return d?d.toLocaleDateString('fr-FR'):'—'}

export default function Home(){
 const sourceRef=useRef<HTMLInputElement>(null),systemRef=useRef<HTMLInputElement>(null);
 const [raw,setRaw]=useState<Row[]>([]),[clean,setClean]=useState<Row[]>([]),[invalid,setInvalid]=useState<Row[]>([]),[missing,setMissing]=useState<Row[]>([]),[system,setSystem]=useState<Row[]>([]);
 const [sourceName,setSourceName]=useState(''),[systemName,setSystemName]=useState(''),[search,setSearch]=useState(''),[tab,setTab]=useState<'all'|'invalid'|'missing'>('all'),[order,setOrder]=useState<'asc'|'desc'>('asc');
 const [working,setWorking]=useState(false),[progress,setProgress]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[modal,setModal]=useState(false),[notice,setNotice]=useState<{text:string;tone:Tone}|null>(null);
 const [verifyInput,setVerifyInput]=useState(''),[verifyResults,setVerifyResults]=useState<Row[]>([]);
 const notify=(text:string,tone:Tone='success')=>{setNotice({text,tone});setTimeout(()=>setNotice(null),2800)};
 const duplicates=Math.max(0,raw.length-invalid.length-clean.length);
 const base=tab==='invalid'?invalid:tab==='missing'?missing:clean;
 const filtered=base.filter(r=>r.imei.includes(search.trim()));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize);
 const quality=raw.length?Math.round(clean.length/raw.length*100):0;
 const hasReport=raw.length>0&&(clean.length>0||invalid.length>0);
 function prepare(rows:Row[],name:string){setRaw(rows);setSourceName(name);setClean([]);setInvalid([]);setMissing([]);setTab('all');setPage(1)}
 async function source(file?:File){if(!file||!/\.txt$/i.test(file.name)){notify('Sélectionnez un fichier TXT','error');return}const rows=parse(await file.text());prepare(rows,file.name);notify(`${rows.length} lignes importées`)}
 function process(rows=raw){if(!rows.length)return;setWorking(true);setProgress(22);setTimeout(()=>setProgress(68),160);setTimeout(()=>{const bad=rows.filter(r=>!r.valid);const unique=[...new Map(rows.filter(r=>r.valid).map(r=>[r.imei,r])).values()];unique.sort((a,b)=>{const av=a.date?.getTime()??Number.MAX_SAFE_INTEGER,bv=b.date?.getTime()??Number.MAX_SAFE_INTEGER;return order==='asc'?av-bv:bv-av});setInvalid(bad);setClean(unique);setMissing([]);setTab('all');setProgress(100);setTimeout(()=>{setWorking(false);setProgress(0)},220);notify(`${unique.length} IMEI uniques et conformes`)},430)}
 function demo(){const rows=parse('12/08/2026\n356938035643809\n356938035643817\n356938035643809\n14/08/2026\n490154203237518\n12345678\n17/08/2026\n352099001761481\n353918052109211');prepare(rows,'exemple_controle_aout.txt');setTimeout(()=>process(rows),60)}
 async function loadSystem(file?:File){if(!file||!/(\.xlsx|\.xls|\.txt)$/i.test(file.name)){notify('Utilisez un fichier Excel ou TXT','error');return}try{let rows:Row[]=[];if(/\.txt$/i.test(file.name))rows=(await file.text()).split(/\r?\n/).filter(Boolean).map(x=>{const parts=x.split(/[,;\t|]/);const imei=(parts[0]||'').trim();return{imei,date:parseDate(parts[1]||''),valid:validImei(imei),fo:(parts[2]||'').trim(),model:(parts[3]||'').trim()}});else{const {readSheet}=await import('read-excel-file/browser');const sheet=await readSheet(file);rows=sheet.slice(1).map(c=>{const imei=String(c[0]??'').trim();return{imei,date:c[1] instanceof Date?c[1]:parseDate(String(c[1]??'')),valid:validImei(imei),fo:String(c[2]??'').trim(),model:String(c[3]??'').trim()}}).filter(r=>r.imei)}setSystem(rows);setSystemName(file.name);setVerifyResults(v=>v.map(r=>({...r,connected:undefined,fo:undefined,model:undefined})));notify(`${rows.length} IMEI chargés depuis la base`)}catch{notify('Impossible de lire ce fichier','error')}}
 function compare(){const ids=new Set(system.map(r=>r.imei));const gaps=clean.filter(r=>!ids.has(r.imei));setMissing(gaps);setTab('missing');setPage(1);notify(`${gaps.length} écart${gaps.length>1?'s':''} détecté${gaps.length>1?'s':''}`,gaps.length?'info':'success')}
 function verifyBlock(){const values=verifyInput.split(/[\s,;]+/).map(v=>v.trim()).filter(Boolean);const results=[...new Set(values)].map(imei=>({imei,date:null,valid:validImei(imei)}));setVerifyResults(results);notify(`${results.length} IMEI vérifié${results.length>1?'s':''}`,results.some(r=>!r.valid)?'info':'success')}
 function compareVerified(){const index=new Map(system.map(r=>[r.imei,r]));const results=verifyResults.map(row=>{const match=index.get(row.imei);return{...row,date:match?.date??null,connected:!!match,fo:match?.fo,model:match?.model}});setVerifyResults(results);const found=results.filter(r=>r.connected).length;notify(`${found} trouvé${found>1?'s':''}, ${results.length-found} non connecté${results.length-found>1?'s':''}`,results.length===found?'success':'info')}
 async function excel(){if(!filtered.length)return;const XLSX=await import('xlsx');const ws=XLSX.utils.aoa_to_sheet([['IMEI','Date','Contrôle'],...filtered.map(r=>[r.imei,fmt(r.date),tab==='missing'?'Manquant':r.valid?'Conforme':reason(r.imei)])]);ws['!cols']=[{wch:18},{wch:14},{wch:30}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Rapport IMEI');XLSX.writeFile(wb,`Rapport_IMEI_${new Date().toISOString().slice(0,10)}.xlsx`);notify('Export Excel généré')}
 async function pdf(){if(!filtered.length)return;const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF();doc.setTextColor(15,96,72);doc.setFontSize(18);doc.text('Rapport de contrôle IMEI',14,20);doc.setFontSize(9);doc.setTextColor(100);doc.text(`Généré le ${new Date().toLocaleDateString('fr-FR')}`,14,28);autoTable(doc,{startY:36,head:[['IMEI','Date','Contrôle']],body:filtered.map(r=>[r.imei,fmt(r.date),tab==='missing'?'Manquant':r.valid?'Conforme':reason(r.imei)]),headStyles:{fillColor:[15,96,72]}});doc.save('Rapport_IMEI.pdf');notify('Rapport PDF généré')}
 const clear=()=>{setRaw([]);setClean([]);setInvalid([]);setMissing([]);setSourceName('');setTab('all')};
 return <main className="app-shell">
  <nav className="topbar"><div className="brand"><span className="brand-mark"><FileCheck2/></span><span><b>IMEI <em>CONNECT</em></b><small>DEVICE CONNECTION TRACKER</small></span></div><div className="local-pill"><ShieldCheck/>Suivi sécurisé des appareils</div></nav>
  <header className="hero"><div><span className="eyebrow"><Sparkles/> SUIVI DES TÉLÉPHONES TERRAIN</span><h1>Chaque téléphone suivi.<br/><em>Chaque connexion identifiée.</em></h1><p>Suivez les IMEI connectés ou non, détectez les appareils manquants et identifiez rapidement les FO qui n’ont pas encore connecté leur téléphone.</p><div className="hero-actions"><button className="verify-button" onClick={()=>setModal(true)}><ShieldCheck/>Vérifier un ou plusieurs IMEI</button><button className="demo-button" onClick={demo}><RefreshCw/>Charger une démonstration</button></div></div><div className="trust-card"><LockKeyhole/><span><b>Suivi fiable et confidentiel</b><small>Vos listes IMEI restent exclusivement dans votre navigateur.</small></span></div></header>
  <div className="workspace"><aside className="control-rail">
   <section className="control-block"><Title n="01" title="Liste à nettoyer" note="TXT · une date suivie des IMEI"/><Drop onClick={()=>sourceRef.current?.click()}><input hidden ref={sourceRef} type="file" accept=".txt" onChange={e=>source(e.target.files?.[0])}/><span className="upload-icon"><Upload/></span><b>Déposez votre fichier ici</b><span>ou cliquez pour parcourir</span><small>Fichier TXT · 10 Mo maximum</small></Drop>{sourceName&&<FileChip name={sourceName} detail={`${raw.length} lignes`} clear={clear}/>}<label className="select-row"><span>Tri des résultats</span><select value={order} onChange={e=>setOrder(e.target.value as 'asc'|'desc')}><option value="asc">Plus ancien d’abord</option><option value="desc">Plus récent d’abord</option></select></label><div className="luhn-note"><Check/><span><b>Validation Luhn active</b><small>Contrôle standard à 15 chiffres</small></span></div><button className="primary-button" disabled={!raw.length||working} onClick={()=>process()}>{working?<LoaderCircle className="spin"/>:<Sparkles/>}{working?`Analyse ${progress} %`:'Nettoyer la liste'}</button>{working&&<div className="progress"><i style={{width:`${progress}%`}}/></div>}</section>
   <section className="control-block"><Title n="02" title="Base de comparaison" note="Optionnel · Excel ou TXT"/><Drop compact onClick={()=>systemRef.current?.click()}><input hidden ref={systemRef} type="file" accept=".xlsx,.xls,.txt" onChange={e=>loadSystem(e.target.files?.[0])}/><Database/><b>Importer la base système</b><span>.xlsx, .xls ou .txt</span></Drop>{systemName&&<FileChip name={systemName} detail={`${system.length} IMEI`} clear={()=>{setSystem([]);setSystemName('');setMissing([])}}/>}<button className="secondary-button" disabled={!clean.length||!system.length} onClick={compare}><FileCheck2/>Comparer les bases</button></section>
   <p className="privacy-note"><ShieldCheck/>Aucun fichier stocké. Aucune donnée transmise.</p>
  </aside><section className="report-card"><header className="report-head"><div><span>RAPPORT DE CONNEXION</span><h2>{hasReport?`${clean.length} téléphones suivis`:'Aucun suivi en cours'}</h2></div><div><button disabled={!filtered.length} onClick={excel}><Download/>Excel</button><button disabled={!filtered.length} onClick={pdf}><FileText/>PDF</button></div></header>
   {!hasReport?<div className="empty-report"><div><FileCheck2/></div><h3>Votre rapport apparaîtra ici</h3><p>Importez une liste, vérifiez directement un bloc d'IMEI ou chargez la démonstration.</p><button className="empty-verify" onClick={()=>setModal(true)}><ShieldCheck/>Vérifier des IMEI maintenant</button><section><span><i>1</i> Importez</span><span><i>2</i> Contrôlez</span><span><i>3</i> Exportez</span></section></div>:<><div className="stat-strip"><Stat label="Importés" value={raw.length}/><Stat label="Conformes" value={clean.length} note={`${quality}% qualité`} tone="green"/><Stat label="Doublons" value={duplicates} tone="amber"/><button onClick={()=>setModal(true)}><Stat label="À vérifier" value={invalid.length} tone="red"/></button>{tab==='missing'&&<Stat label="Manquants" value={missing.length} tone="purple"/>}</div><div className="report-toolbar"><div className="tabs"><button className={tab==='all'?'active':''} onClick={()=>{setTab('all');setPage(1)}}>Tous <b>{clean.length}</b></button><button className={tab==='invalid'?'active danger':''} onClick={()=>{setTab('invalid');setPage(1)}}>À vérifier <b>{invalid.length}</b></button>{missing.length>0&&<button className={tab==='missing'?'active':''} onClick={()=>{setTab('missing');setPage(1)}}>Manquants <b>{missing.length}</b></button>}</div><label className="search-box"><Search/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Rechercher un IMEI"/></label></div>{!shown.length?<div className="no-results"><Search/><h3>Aucun résultat</h3></div>:<><div className="table-wrap"><table><thead><tr><th>IMEI</th><th>Date associée</th><th>Contrôle</th><th></th></tr></thead><tbody>{shown.map((r,i)=><tr key={`${r.imei}-${i}`}><td><i className="row-index">{String((page-1)*pageSize+i+1).padStart(2,'0')}</i><span className="mono">{r.imei}</span></td><td>{fmt(r.date)}</td><td><span className={`status-badge ${tab==='missing'?'missing':r.valid?'valid':'invalid'}`}>{tab==='missing'?<><CircleAlert/>Manquant</>:r.valid?<><Check/>Conforme</>:<><AlertTriangle/>{reason(r.imei)}</>}</span></td><td><button className="copy-button" onClick={()=>navigator.clipboard.writeText(r.imei)}><Copy/></button></td></tr>)}</tbody></table></div><footer className="table-footer"><span>{filtered.length} résultat{filtered.length>1?'s':''}</span><label>Afficher <select value={pageSize} onChange={e=>{setPageSize(+e.target.value);setPage(1)}}><option>25</option><option>50</option><option>100</option></select></label><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></footer></>}</>}
  </section></div>
  <footer className="site-footer"><b>IMEI CONNECT</b><span>SUIVI DES APPAREILS · IDENTIFICATION DES ÉCARTS · AUCUN STOCKAGE DISTANT</span><b>v2.1</b></footer>
  {modal&&<VerifierModal onClose={()=>setModal(false)} input={verifyInput} setInput={value=>{setVerifyInput(value);setVerifyResults([])}} results={verifyResults} fallback={invalid} systemName={systemName} systemCount={system.length} onVerify={verifyBlock} onCompare={compareVerified} onClear={()=>{setVerifyInput('' );setVerifyResults([])}}/>}
  {notice&&<div className={`toast ${notice.tone}`}>{notice.tone==='error'?<CircleAlert/>:notice.tone==='info'?<Info/>:<Check/>}{notice.text}</div>}
 </main>
}
function Title({n,title,note}:{n:string;title:string;note:string}){return <div className="section-label"><i>{n}</i><span><b>{title}</b><small>{note}</small></span></div>}
function Drop({children,onClick,compact=false}:{children:React.ReactNode;onClick:()=>void;compact?:boolean}){return <div className={`dropzone ${compact?'compact':''}`} role="button" tabIndex={0} onClick={onClick} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&onClick()}>{children}</div>}
function FileChip({name,detail,clear}:{name:string;detail:string;clear:()=>void}){return <div className="file-chip"><FileCheck2/><span><b>{name}</b><small>{detail}</small></span><button onClick={clear}><X/></button></div>}
function Stat({label,value,note,tone='neutral'}:{label:string;value:number;note?:string;tone?:string}){return <article className={`stat ${tone}`}><small>{label}</small><strong>{value}</strong>{note&&<span>{note}</span>}</article>}

function VerifierModal({onClose,input,setInput,results,fallback,systemName,systemCount,onVerify,onCompare,onClear}:{onClose:()=>void;input:string;setInput:(value:string)=>void;results:Row[];fallback:Row[];systemName:string;systemCount:number;onVerify:()=>void;onCompare:()=>void;onClear:()=>void}){
 const [detailFilter,setDetailFilter]=useState<'all'|'connected'|'missing'>('all');
 const compared=results.some(row=>row.connected!==undefined);
 const connected=results.filter(row=>row.connected).length;
 const missingCount=results.length-connected;
 const source=results.length?results:fallback;
 const displayed=compared?source.filter(row=>detailFilter==='all'||(detailFilter==='connected'?row.connected:!row.connected)):source;
 async function exportDetails(){const XLSX=await import('xlsx');const ws=XLSX.utils.aoa_to_sheet([['IMEI','Validation','Connexion','FO','Modèle','Date dans la base'],...results.map(row=>[row.imei,row.valid?'Conforme':reason(row.imei),row.connected?'Connecté':'Non connecté',row.fo||'',row.model||'',fmt(row.date)])]);ws['!cols']=[{wch:18},{wch:24},{wch:16},{wch:22},{wch:22},{wch:18}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Détail connexions');XLSX.writeFile(wb,`Resultat_Connexions_IMEI_${new Date().toISOString().slice(0,10)}.xlsx`)}
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="invalid-modal verifier-modal" onMouseDown={e=>e.stopPropagation()}>
  <header><div><CircleAlert/><span><b>Vérification et comparaison IMEI</b><small>Contrôlez vos numéros puis comparez-les à la base système</small></span></div><button onClick={onClose} aria-label="Fermer"><X/></button></header>
  <div className="manual-check"><label htmlFor="imei-check">IMEI à contrôler</label><textarea id="imei-check" value={input} onChange={e=>setInput(e.target.value)} placeholder={'Collez un IMEI ou plusieurs IMEI\nUn numéro par ligne, séparés par espace, virgule ou point-virgule'}/><div><span>{input.split(/[\s,;]+/).filter(Boolean).length} numéro(s) détecté(s)</span><button disabled={!input.trim()} onClick={onVerify}><ShieldCheck/>Vérifier maintenant</button></div></div>
  {results.length>0&&<><div className="check-summary"><span className="ok"><Check/>{results.filter(r=>r.valid).length} conforme(s)</span><span className="bad"><AlertTriangle/>{results.filter(r=>!r.valid).length} invalide(s)</span>{compared&&<><span className="connected"><Database/>{connected} connecté(s)</span><span className="missing"><CircleAlert/>{missingCount} non connecté(s)</span></>}<button onClick={onClear}>Effacer</button></div><div className="compare-verified"><div><Database/><span><b>{systemName||'Base système non chargée'}</b><small>{systemCount?`${systemCount} IMEI disponibles`:'Importez une base Excel ou TXT depuis l’écran principal'}</small></span></div><button disabled={!systemCount} onClick={onCompare}><FileCheck2/>Comparer à la base</button></div></>}
  {compared&&<div className="detail-toolbar"><div><button className={detailFilter==='all'?'active':''} onClick={()=>setDetailFilter('all')}>Tous <b>{results.length}</b></button><button className={detailFilter==='connected'?'active connected':''} onClick={()=>setDetailFilter('connected')}>Connectés <b>{connected}</b></button><button className={detailFilter==='missing'?'active missing':''} onClick={()=>setDetailFilter('missing')}>Non connectés <b>{missingCount}</b></button></div><button className="detail-export" onClick={exportDetails}><Download/>Exporter le détail</button></div>}
  <p><Info/>La comparaison recherche chaque IMEI vérifié dans la base système importée.</p>
  <div className="modal-table"><table><thead><tr><th>IMEI contrôlé</th><th>Validation</th><th>Connexion</th><th>FO</th><th>Modèle</th><th>Date base</th></tr></thead><tbody>{displayed.map((row,i)=><tr key={`${row.imei}-${i}`}><td className="mono">{row.imei}</td><td><span className={`status-badge ${row.valid?'valid':'invalid'}`}>{row.valid?<><Check/>Conforme</>:<><AlertTriangle/>{reason(row.imei)}</>}</span></td><td>{row.connected===undefined?<span className="pending-status">Non comparé</span>:<span className={`status-badge ${row.connected?'valid':'missing'}`}>{row.connected?<><Check/>Connecté</>:<><CircleAlert/>Non connecté</>}</span>}</td><td><span className="fo-details"><b>{row.fo||'—'}</b></span></td><td>{row.model||'—'}</td><td>{row.connected?fmt(row.date):'—'}</td></tr>)}</tbody></table></div>
 </section></div>
}


